[global]
# Global configuration for Streamlit Cloud deployment

[server]
# Server configuration
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
# Browser configuration
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
# Theme configuration
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[runner]
# Runner configuration
magicEnabled = true
